return {
  'Mr-LLLLL/treesitter-outer',
  dependencies = "nvim-treesitter/nvim-treesitter",
  -- only load this plug in follow filetypes
  ft = {
    "c",
    "cpp",
    "elixir",
    "fennel",
    "foam",
    "go",
    "javascript",
    "julia",
    "lua",
    "nix",
    "php",
    "python",
    "r",
    "ruby",
    "rust",
    "scss",
    "tsx",
    "typescript",
  },
  -- default config
  opts = {
    filetypes = {
      "c",
      "cpp",
      "elixir",
      "fennel",
      "foam",
      "go",
      "javascript",
      "julia",
      "lua",
      "nix",
      "php",
      "python",
      "r",
      "ruby",
      "rust",
      "scss",
      "tsx",
      "typescript",
    },
    mode = { 'n', 'v' },
    prev_outer_key = "[{",
    next_outer_key = "]}",
  },
}
